<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBEINxJm\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBEINxJm/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBEINxJm.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBEINxJm\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerBEINxJm\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'BEINxJm',
    'container.build_id' => '489ca9a2',
    'container.build_time' => 1575989896,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBEINxJm');
